@startuml Car

class LinkablePart <<abstract>> {
    {abstract} +void execute(float p_pression)
}


class Wheel {
    +void executeRotation(float p_force)
}

class Gear {
    -int demultiplier
}

class GearLever {
    -level
    - Gear gears[]
    +void change(void)
    +Gear* activeGear()
}


class Singleton< GearLever > {

}


class Transmission {
    -vector<Wheel *> wheels
    +void activate(float p_force)
}

class Crankshaft {
    -Transmission* trans
    +void receiveForce(float p_volume);
}


class ExplosionChamber {
    -Crankshaft* crank
    +void fill(float p_volume)
}

class Injector {
    -ExplosionChamber* chamber
    +void execute(float p_pression)
}



class Motor {
    -Injector inj
    -ExplosionChamber chamber

    -Crankshaft shaft
    +void connectToTransmission(Transmission p_transmission)
}


class Pedal {
    -LinkablePart* part
    +void setTarget(LinkablePart* p_part)
    +void use(float p_pression)
}


class Direction {
    -Wheel wheels[]
    +void turn(float p_angle)
}



class DAE {
    -Direction* dir
    -float force
    +void use(float p_angle)
}



class SteerWheel {
    -DAE* dae
    -float force
    +void turn(float p_angle)
}



class Brake {
    -Wheel* wheel
    +void execute(float p_force)
    +void attackWheel(Wheel* p_wheel)
}



class BrakeController {
    -Brake brakes[]
    +void execute(float p_pression)
}



class Cockpit {
    -Pedal pedal
    -SteerWheel steer
    -GearLever lever
    +void pressPedal(float p_pression)
    +void steer(float p_angle)
    +void changeGear(void)
}



class Electronics {
    -DAE dae
}



class Car {
    -BrakeController brakes
    -Direction dir
    -Transmission trans
    -Motor motor
    -Electronics elec
    -Cockpit pit
}

' RELATIONSHIPS

GearLever --* Gear

Singleton --|> GearLever

Crankshaft o- ExplosionChamber


Transmission o-- Crankshaft

ExplosionChamber o- Injector

Motor --* Injector
Motor --* ExplosionChamber
Motor --* Crankshaft
Transmission <- Motor

LinkablePart o-- Pedal

Direction --* Wheel

Direction o-- DAE

SteerWheel -o DAE

Brake --o Wheel

BrakeController --* Brake

Cockpit --* Pedal
Cockpit --* SteerWheel
Cockpit --* GearLever


Electronics --* DAE

Car --* BrakeController
Car --* Direction
Car --* Transmission
Car --* Motor
Car --* Electronics
Car --* Cockpit



LinkablePart --|> BrakeController
LinkablePart --|> Injector

Transmission --o Wheel

' ORGANISATION

Electronics -[hidden]> Direction
Direction -[hidden]> Transmission
Motor-[hidden]>BrakeController
Cockpit -[hidden]> Electronics
Singleton -[hidden]> Cockpit
GearLever -[hidden]>Pedal
Pedal -[hidden]> SteerWheel
Injector -[hidden]> Brake

@enduml
