@startuml Car

class LinkablePart <<abstract>> {
    {abstract} +void execute(float p_pression)
}
LinkablePart --|> BrakeController
LinkablePart --|> Injector

class Wheel {
    +void executeRotation(float p_force)
}

class Gear {
    -int demultiplier
}

class GearLever {
    -level
    - Gear gears[]
    +void change(void)
    +Gear* activeGear()
}
GearLever --* Gear

class Singleton< GearLever > {

}
Singleton --|> GearLever

class Transmission {
    -vector<Wheel *> wheels
    +void activate(float p_force)
}

class Crankshaft {
    -Transmission* trans
    +void receiveForce(float p_volume);
}
Crankshaft --o Transmission


class ExplosionChamber {
    -Crankshaft* crank
    +void fill(float p_volume)
}
ExplosionChamber --o Crankshaft

class Injector {
    -ExplosionChamber* chamber
    +void execute(float p_pression)
}
Injector --o ExplosionChamber


class Motor {
    -Injector inj
    -ExplosionChamber chamber
    -Crankshaft shaft
    +void connectToTransmission(Transmission p_transmission)
}
Motor --* Injector
Motor --* ExplosionChamber
Motor --* Crankshaft
Motor -> Transmission


class Pedal {
    -LinkablePart* part
    +void setTarget(LinkablePart* p_part)
    +void use(float p_pression)
}
Pedal --o LinkablePart


class Direction {
    -Wheel wheels[]
    +void turn(float p_angle)
}
Direction --* Wheel


class DAE {
    -Direction* dir
    -float force
    +void use(float p_angle)
}
DAE --o Direction


class SteerWheel {
    -DAE* dae
    -float force
    +void turn(float p_angle)
}
SteerWheel --o DAE


class Brake {
    -Wheel* wheel
    +void execute(float p_force)
    +void attackWheel(Wheel* p_wheel)
}
Brake --o Wheel


class BrakeController {
    -Brake brakes[]
    +void execute(float p_pression)
}
BrakeController --* Brake


class Cockpit {
    -Pedal pedal
    -SteerWheel steer
    -GearLever lever
    +void pressPedal(float p_pression)
    +void steer(float p_angle)
    +void changeGear(void)
}
Cockpit --* Pedal
Cockpit --* SteerWheel
Cockpit --* GearLever


class Electronics {
    -DAE dae
}
Electronics --* DAE


class Car {
    -BrakeController brakes
    -Direction dir
    -Transmission trans
    -Motor motor
    -Electronics elec
    -Cockpit pit
}
Car --* BrakeController
Car --* Direction
Car --* Transmission
Car --* Motor
Car --* Electronics
Car --* Cockpit




@enduml
